package br.com.infogest.views;

import br.com.infogest.dao.ConexaoDao;
import br.com.infogest.model.Contas;
import br.com.infogest.model.ContasDao;
import br.com.infogest.model.Despesas;
import br.com.infogest.model.DespesasEmpress;
import br.com.infogest.model.Receitas;
import br.com.infogest.model.Transacoes;
import br.com.infogest.model.Usuarios;
import java.sql.*;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    // Metodo verificar e logar
    public void logar() {
        String sql = "SELECT * FROM usuarios WHERE email = ? AND senha = md5(?)";

        try {
            // Preparar consulta ao banco
            conexao = ConexaoDao.conectar();
            pst = conexao.prepareStatement(sql);
            pst.setString(1, textUser.getText());
            //metodo de captura de senha mais segura
            String senha = new String(textSenha.getPassword());
            pst.setString(2, senha);

            // Executar a consulta (query);
            rs = pst.executeQuery();

            // Estrutura de verificação de existencia
            if (rs.next()) {
                String userName = rs.getString(2);
                Usuarios.setNome(userName);
                
                String email = rs.getString(3);
                Usuarios.setEmail(email);
                
                int idUser = rs.getInt(1);
                Despesas.setUsuario_id(idUser);
                Receitas.setUsuario_id(idUser);
                DespesasEmpress.setUsuario_id(idUser);
                Usuarios.setId(idUser);
                Transacoes.setUsuarioID(idUser);
                Contas.setUsuario_id(idUser);
                
                // Obter o conteudo da coluna tipo da tabela usuários do banco
                String tipo = rs.getString(5);
                Usuarios.setTipo(tipo);
                Transacoes.setTipo(tipo);
                
                if (tipo.equals("Empresarial")) {
                    // Função que irá exibir a tela principal
                    Principal principal = new Principal();
                    principal.setVisible(true);
                    Principal.btnReceitas.setEnabled(true);
                    Principal.btnDetRend.setEnabled(true);
                    this.dispose();
                } else {
                    Principal principal = new Principal();
                    principal.setVisible(true);
                    Principal.btnDetalheCont.setEnabled(true);
                    
                    ContasDao cont = new ContasDao();
                    cont.buscarSaldo();
                    
                    this.dispose();
                }

                // fechar conexao com banco
                conexao.close();
                pst.close();
            } else {
                JOptionPane.showMessageDialog(this, "Usuário e/ou senha inválido!");
            }
        } catch (HeadlessException | SQLException error) {
            JOptionPane.showMessageDialog(this, error);
        }
    }

    /**
     * Creates new form TelaLogin
     */
    public Login() {
        initComponents();
        conexao = br.com.infogest.dao.ConexaoDao.conectar();
        System.out.println(conexao);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textUser = new javax.swing.JTextField();
        textSenha = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblCadastarButon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Usuário");

        jLabel2.setText("Senha");

        btnLogin.setText("Logar");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jLabel3.setText("Não possui uma conta?");

        lblCadastarButon.setForeground(new java.awt.Color(51, 51, 255));
        lblCadastarButon.setText("Cadastrar");
        lblCadastarButon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCadastarButonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCadastarButon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(btnLogin))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(textUser))))
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(jLabel3)
                    .addComponent(lblCadastarButon))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        setBounds(0, 0, 443, 245);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        logar();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void lblCadastarButonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadastarButonMouseClicked
        Cadastro cadastro = new Cadastro();
        cadastro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblCadastarButonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblCadastarButon;
    private javax.swing.JPasswordField textSenha;
    private javax.swing.JTextField textUser;
    // End of variables declaration//GEN-END:variables
}
